tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed": "#ffdbc8",
                "on-surface": "#e5e2e1",
                "tertiary-container": "#e47011",
                "surface-variant": "#353535",
                "on-tertiary": "#522300",
                "background": "#131313",
                "on-primary-fixed-variant": "#004397",
                "primary-fixed": "#d8e2ff",
                "on-background": "#e5e2e1",
                "on-error-container": "#ffdad6",
                "secondary-container": "#5672fe",
                "surface-container-lowest": "#0e0e0e",
                "primary": "#aec6ff",
                "on-primary": "#002e6b",
                "on-primary-fixed": "#001a43",
                "error": "#ffb4ab",
                "outline-variant": "#424754",
                "surface-container-highest": "#353535",
                "error-container": "#93000a",
                "surface-container-low": "#1c1b1b",
                "secondary": "#5672fe",
                "inverse-on-surface": "#313030",
                "on-surface-variant": "#c2c6d6",
                "surface-container": "#20201f",
                "on-tertiary-container": "#481e00",
                "on-tertiary-fixed": "#321300",
                "surface-tint": "#aec6ff",
                "inverse-surface": "#e5e2e1",
                "on-error": "#690005",
                "secondary-fixed-dim": "#5672fe",
                "surface-dim": "#131313",
                "on-secondary-fixed": "#5672fe",
                "on-secondary-container": "#5672fe",
                "tertiary": "#ffb68b",
                "primary-fixed-dim": "#aec6ff",
                "on-secondary": "#5672fe",
                "surface": "#131313",
                "tertiary-fixed-dim": "#ffb68b",
                "surface-container-high": "#2a2a2a",
                "on-tertiary-fixed-variant": "#753400",
                "outline": "#8c90a0",
                "on-primary-container": "#00275e",
                "inverse-primary": "#0059c5",
                "on-secondary-fixed-variant": "#5672fe",
                "surface-bright": "#393939",
                "secondary-fixed": "#5672fe",
                "primary-container": "#508dff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "gutter": "16px",
                "stack-lg": "24px",
                "margin-mobile": "12px",
                "stack-md": "12px",
                "stack-tight": "4px",
                "container-max": "1280px",
                "margin-desktop": "24px"
            },
            "fontFamily": {
                "body-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-md": ["Inter"],
                "headline-lg": ["Inter"],
                "label-bold": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-sm": ["Inter"]
            },
            "fontSize": {
                "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "label-md": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
                "headline-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
                "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "label-bold": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
                "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "700"}],
                "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}]
            }
        },
    },
}
